<?php


namespace keystorage;


class Module extends \yii\base\Module
{
    public $controllerNamespace = 'keystorage\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}