<?php

namespace backend\modules\system\components\services;

use common\components\providers\BaseServiceProvider;
use common\constants\BaseConstant;

class SystemServiceProvider extends BaseServiceProvider
{
    public function init()
    {
        switch ($this->type) {
            case BaseConstant::METHOD_DB:
                $this->service = new DbService($this->config[BaseConstant::METHOD_DB]);
                break;
        }
        parent::init(); // TODO: Change the autogenerated stub
    }
}