<?php
/**
 * This is the template for generating a repository provider class within a module.
 */

/* @var $this yii\web\View */
/* @var $generator \common\gii\module\Generator */

echo "<?php\n";
?>

namespace <?= $generator->getRepositoryNamespace() ?>;

use common\components\providers\BaseRepositoryProvider;
use common\constants\BaseConstant;

class <?= $generator->getTemplateName() ?>RepositoryProvider extends BaseRepositoryProvider
{
    public function init()
    {
        switch ($this->type) {
            case BaseConstant::METHOD_DB:
                $this->repository = new DbRepository($this->config[BaseConstant::METHOD_DB]);
                break;
        }
        parent::init(); // TODO: Change the autogenerated stub
    }
}