<?php
/**
 * This is the template for generating a service provider class within a module.
 */

/* @var $this yii\web\View */
/* @var $generator \common\gii\module\Generator */

echo "<?php\n";
?>

namespace <?= $generator->getServiceNamespace() ?>;

use common\components\providers\BaseServiceProvider;
use common\constants\BaseConstant;

class <?= $generator->getTemplateName() ?>ServiceProvider extends BaseServiceProvider
{
    public function init()
    {
        switch ($this->type) {
            case BaseConstant::METHOD_DB:
                $this->service = new DbService($this->config[BaseConstant::METHOD_DB]);
                break;
        }
        parent::init(); // TODO: Change the autogenerated stub
    }
}