<?php


namespace common\components\providers;


use common\components\services\BaseApiService;
use common\components\services\BaseDataService;
use common\components\services\BaseDbService;
use common\components\services\BaseElasticsearchService;
use yii\base\Exception;

class BaseServiceProvider extends BaseProvider
{
    /**
     * @var  BaseDbService | BaseApiService | BaseElasticsearchService | BaseDataService $service
     */
    protected $service = false;

    /**
     * @throws Exception
     */
    public function init()
    {
        $this->component = $this->service;

        parent::init(); // TODO: Change the autogenerated stub
    }
}