<?php

use admin\components\Configs;
use yii\db\Migration;

/**
 * Class m210714_160353_seed_default_menu
 */
class m210714_160353_seed_default_menu extends Migration
{
    public function init()
    {
        $this->db = Configs::db();
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $menuTable = Configs::instance()->menuTable;
        $this->batchInsert($menuTable, ['id', 'name', 'parent', 'route', 'order', 'data'],
            [
                [1, 'System Management', NULL, NULL, 20, '$icon = \'<i class="nav-icon fas fa-cogs"></i>\';'],

                [2, 'Users', 1, '', 1, '$icon = \'<i class="nav-icon fas fa-users"></i>\';'],
                [3, 'Roles and Permissions', 1, '/admin/assignment/index', 2, '$icon = \'<i class="fas fa-users-cog"></i>\';'],
                [5, 'Menu', 1, '/admin/menu/index', 3, '$icon = \'<i class="nav-icon fas fa-list-ul"></i>\';'],
                [7, 'Cache', 1, '/system/cache/index', 4, '$icon = \'<i class="nav-icon fas fa-eraser"></i>\';'],
                [8, 'Gii', 1, '/gii', 5, '$icon = \'<i class="nav-icon fas fa-tools"></i>\';'],
                [9, 'Log', 1, NULL, 6, '$icon = \'<i class="nav-icon fas fa-clipboard-list"></i>\';'],

                [10, 'Audit Log', 7, '/audit/default/index', 1, '$icon = \'<i class="nav-icon fas fa-file-alt"></i>\';'],
            ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $menuTable = Configs::instance()->menuTable;
        $this->truncateTable($menuTable);
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m210714_160353_seed_default_menu cannot be reverted.\n";

        return false;
    }
    */
}
