<?php

use admin\components\Configs;
use yii\db\Migration;
use admin\constants\Constant;

class m210524_201442_init_user extends Migration
{
    public function init()
    {
        $this->db = Configs::userDb();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function up()
    {
        $userTable = Configs::instance()->userTable;
        $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB';

        $this->createTable($userTable, [
            'id' => $this->primaryKey(),
            'uuid' => $this->string(36)->notNull()->unique(),
            'username' => $this->string()->notNull()->unique(),
            'auth_key' => $this->string(32)->notNull(),
            'password_hash' => $this->string()->notNull(),
            'password_reset_token' => $this->string()->unique(),
            'email' => $this->string()->notNull()->unique(),
            'phone' => $this->string()->notNull(),
            'status' => $this->smallInteger()->notNull()->defaultValue(Constant::STATUS_USER_ACTIVE),
            'logged_at' => $this->dateTime(),
            'created_at' => $this->dateTime(),
            'updated_at' => $this->dateTime(),
        ], $tableOptions);
    }

    public function down()
    {
        $userTable = Configs::instance()->userTable;
        $this->dropTable($userTable);
    }
}
