<?php


namespace common\components\models;


use common\behaviors\DateTimeBehavior;
use Ramsey\Uuid\Uuid;
use yii\db\ActiveRecord;
use function Ramsey\Uuid\v4;

class DbActiveRecord extends ActiveRecord
{
    public function behaviors()
    {
        return [
            DateTimeBehavior::class
        ]; // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if (isset($this->uuid)) {
            $this->uuid = v4();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}