<?php

namespace backend\modules\user\components\repositories;

use common\components\providers\BaseRepositoryProvider;
use common\constants\BaseConstant;

class UserRepositoryProvider extends BaseRepositoryProvider
{
    public function init()
    {
        switch ($this->type) {
            case BaseConstant::METHOD_DB:
                $this->repository = new DbRepository($this->config[BaseConstant::METHOD_DB]);
                break;
        }
        parent::init(); // TODO: Change the autogenerated stub
    }
}